### ISSUE TITLE
Accessing public API methods

### ISSUE THREAD

**Issue by kjfdebruin** [yanick/vue-svg-pan-zoom#1]
Thanks for a great repo!
Is there a way to access the [public API methods](https://github.com/ariutta/svg-pan-zoom#public-api) like `zoomIn()`?

**Comment by yanick** [comment]
Thanks! And not right now, as the object returned by `svgpanzoom()` is not stored for later access, but that shouldn't be hard. Let's see if I can add that over the week-end. :-)  Or you can have a go at it, if you feel brave!

**Comment by yanick** [comment]
I have a working prototype at https://github.com/yanick/vue-svg-pan-zoom/tree/svgpanzoom-event 

Now I need to make it a little more robust and add documentation.

**Comment by yanick** [comment]
Done!

**Comment by rene2u9** [comment]
could you provide a example accessing zoomAtPoint or any other method of the svgPanZoom public api?
.. i have trouble to invoke it using typescript
